version: '3.8'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    networks:
      - app-net

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    networks:
      - app-net

volumes:
  db_data:
  wordpress_data:

networks:
  app-net:
    driver: bridge
