version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - /var/www/html:/var/www/html  # Asumiendo que /var/www/html es un montaje NFS ya configurado
    environment:
      WORDPRESS_DB_HOST: 172.31.22.39  # Reemplaza con la IP privada de tu instancia de DB
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    ports:
      - "80:80"
    networks:
      - app-net

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      WORDPRESS_DB_HOST: 172.31.22.39  # Reemplaza con la IP de la instancia de DB
      WORDPRESS_DB_USER: exampleuser  # Asegúrate de que estos valores coincidan
      WORDPRESS_DB_PASSWORD: examplepass  # con los que configuraste en tu instancia DB
      WORDPRESS_DB_NAME: exampledb
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
